### PR TITLE
Update locales.go

### PR DESCRIPTION
**Pull request by hasantayyar**
Type changes

### CODE REVIEW

**Comment by theSoenke** [comment]
Thanks for your contribution. Unfortunately this code is not maintained anymore and will likely soon be removed. This has been only a simple prototype for testing over the air translations. Are you already using or currently exploring to use this code in production? And if that is the case would you like to share more details about your use case with us? You can also contact us at https://phraseapp.com/contact We've also recently started to provide an official over the air translations solution. This is currently in private beta but if you are interested we will happily enable it for you

**Comment by hasantayyar** [comment]
Oh, I was experimenting some caching layers. 
We are already using phraseapp on production and some other solutions for this caching purpose. 

Besides go client is good enough!

**Comment by hasantayyar** [comment]
(This can be closed then)

**Comment by theSoenke** [comment]
Thanks for the info. Let us now if we can do something to make this easier for you. We've also recently released a beta version of the client which caches locale files. Although this probably serves a slightly different purpose than how you using caches https://github.com/phrase/phraseapp-client/releases/tag/1.13.0-beta

**Comment by hasantayyar** [comment]
that is good news! Thanks.

**Pull request closed without merging**
